# Generated by Django 4.0.4 on 2022-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
