# Generated by Django 4.0.4 on 2022-05-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_period_period_id_alter_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='period_id',
        ),
        migrations.AddField(
            model_name='practis',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
