# Generated by Django 4.0.4 on 2022-05-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practis',
            new_name='PracticeWorker',
        ),
    ]
